spring.application.name=todo-jwt

# Web Server Port
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/todo_jwt_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Eve18605090708!

# Hibernate DDL Auto (update ???????/???????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LINE Bot setting
line.bot.channel-secret=7bb576690bebc72149aad81669fdc87d
line.bot.channel-token=T1NPLUkG2oyFfRGDNSxMhrpZBEgL5bcRuxfxyJuLOMw7W3/7J6Sx/FHiLP7jpu5jn4ROFj0up/OWdRAnEvywF/MpbhAxGI1DRWIiGfnCrKjBnoqLAHKuOE2Q7S/GljCg+1hf9KDLh3+9nJcXDI42LwdB04t89/1O/w1cDnyilFU=
line.bot.handler.path=/callback